### ISSUE TITLE
Flashing fails

### ISSUE THREAD

**Issue by midzer** [Alex313031/ChromiumOS#2]
Hi,

I've downloaded latest .7z and extracted the image. Then used Etcher to flash it. After validation it fails, see

![2021-12-07_17-17](https://user-images.githubusercontent.com/6484844/145066310-92518189-e38f-4e2d-b9b6-facd887e5cf2.png)

In fact there is data on it. And it does boot from it. But after selecting

* local image A

laptop seems to not continue.

What am I doing wrong?

Greets
midzer

**Comment by Alex313031** [comment]
@midzer Issue with etcher not chromiumos, for anyone who comes across this, please use https://github.com/balena-io/etcher/releases/tag/v1.5.122

**Comment by Alex313031** [comment]
@midzer Also, there is a slight chance (depending on alot of factors both in chromiumos and in your specific UEFI firmware) that it might not boot in EFI mode, and you might have to temporarily set your bios to use CSM i.e. actual old style BIOS. I didn't know that any sandy bridge boards used UEFI thats interesting.

**Comment by Alex313031** [comment]
@midzer Only thing missing from ChromiumOS is google drive support in the files app, and widevine (if you enable lacros in chrome://flags you can use widevine but I want it natively built in the image) Work has already started on enabling these, and once it is done, the only difference between my releases and ChromeOS will be ARC++ (android app support)

**Comment by Alex313031** [comment]
Are you on any social media, where we can chat about stuff, so we don't have to do it here?
Like I was gonna ask, have you used ChromiumOS/ChromeOS before and are you familiar with some of its nuances?

**Comment by midzer** [comment]
@Alex313031 I've followed you on Twitter. You can follow me there...

**Comment by Alex313031** [comment]
Oh ok

**Comment by midzer** [comment]
Flashing works now properly. I close this one for good.

**Comment by crocer211** [comment]
know this was closed but it actually does succeed in flashing with that error thats just a verification error and i know you fixed it
